---
- name: My Ansible Playbook
  hosts: web-servers
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      copy:
        content: "<h1>Hello from {{ ansible_hostname }}!</h1>"
        dest: /var/www/html/index.html
